version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8080:8000"
    volumes:
      - ./app:/var/www/html
    depends_on:
      db:
        condition: service_healthy # Условие запуска после готовности базы данных
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=tekCheburkek!23opq
      - REDIS_HOST=redis

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: tekCheburkek!23opq
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -d laravel"]
      interval: 10s  # Интервал между проверками
      timeout: 5s    # Максимальное время ожидания ответа
      retries: 5     # Количество попыток проверки

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"